services:
  - type: web
    name: smartcart-backend
    env: java
    rootDir: backend
    buildCommand: mvn -DskipTests clean package
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar
    plan: free
